services:
  postgres:
    image: postgres:17
    container_name: postgres_database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - nidus_go_docker

  app:
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: on-failure
    env_file:
      - .env
    volumes:
      - api:/usr/src/app
    depends_on:
      - postgres
    networks:
      - nidus_go_docker

volumes:
  database_postgres:
  api:

networks:
  nidus_go_docker: